{
  "hash": "267e465e28823ffa50ca039602665901",
  "result": {
    "markdown": "---\ntitle: \"Difference-in-Differences\"\n---\n\n\n\n\n## Mean satisfaction for treated and control hospitals\n\n\n::: {.cell hash='08_did_cache/html/unnamed-chunk-2_a55c53b3548e11eb92d78d85219c8504'}\n\n```{.r .cell-code}\n# Treated hospitals before the treatment\nmean(dplyr::pull(dplyr::filter(hospdd, hospital >= 1, hospital <= 18, procedure==0), satis))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 3.525383\n```\n:::\n\n```{.r .cell-code}\n# Treated hospitals after the treatment\nmean(dplyr::pull(dplyr::filter(hospdd, hospital >= 1, hospital <= 18, procedure==1), satis))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 4.363351\n```\n:::\n\n```{.r .cell-code}\n# Control hospitals (without treatment)\nmean(dplyr::pull(dplyr::filter(hospdd, hospital > 18, procedure==0), satis))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 3.387499\n```\n:::\n:::\n\n\n1. Mean satisfaction for treated hospitals before the treatment: 3.525383\n2. Mean satisfaction for treated hospitals after the treatment: 4.363351\n3. Mean satisfaction for control hospitals (without treatment): 3.387499\n\n## Linear regression\n\n\n::: {.cell hash='08_did_cache/html/unnamed-chunk-3_9ddd591db825dc000722dd68e6faefdf'}\n\n```{.r .cell-code}\n# Treated hospitals before introduction\ndf_A1_lm <- (dplyr::filter(hospdd, hospital >= 1, hospital <= 18, procedure == 0))\n# Treated hospitals after introduction\ndf_A2_lm <- (dplyr::filter(hospdd, hospital >= 1, hospital <= 18, procedure == 1))\n# Control hospitals\ndf_B_lm <- (dplyr::filter(hospdd, hospital > 18))\n```\n:::\n\n\n1. Linear regression on treated hospitals before introduction\n\n\n::: {.cell hash='08_did_cache/html/unnamed-chunk-4_2878eb030d2a1792de242130e62104d8'}\n\n```{.r .cell-code}\nsummary(lm(satis ~ as.factor(hospital) + as.factor(month), data = df_A1_lm))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satis ~ as.factor(hospital) + as.factor(month), \n#>     data = df_A1_lm)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -3.1353 -0.4757 -0.0048  0.4740  3.8750 \n#> \n#> Coefficients:\n#>                        Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)            3.228870   0.080191  40.265  < 2e-16 ***\n#> as.factor(hospital)2   0.288897   0.112740   2.562 0.010488 *  \n#> as.factor(hospital)3   0.452987   0.115801   3.912 9.57e-05 ***\n#> as.factor(hospital)4   0.311332   0.107923   2.885 0.003973 ** \n#> as.factor(hospital)5  -0.274068   0.107923  -2.539 0.011201 *  \n#> as.factor(hospital)6   0.368605   0.107923   3.415 0.000654 ***\n#> as.factor(hospital)7   1.335041   0.104296  12.801  < 2e-16 ***\n#> as.factor(hospital)8   0.047233   0.111393   0.424 0.671609    \n#> as.factor(hospital)9  -1.551302   0.114204 -13.584  < 2e-16 ***\n#> as.factor(hospital)10  1.572914   0.112740  13.952  < 2e-16 ***\n#> as.factor(hospital)11  0.162248   0.111393   1.457 0.145453    \n#> as.factor(hospital)12 -0.073736   0.114204  -0.646 0.518602    \n#> as.factor(hospital)13  0.462809   0.110148   4.202 2.80e-05 ***\n#> as.factor(hospital)14  0.141160   0.115801   1.219 0.223038    \n#> as.factor(hospital)15 -0.300102   0.115801  -2.592 0.009647 ** \n#> as.factor(hospital)16  1.376744   0.112740  12.212  < 2e-16 ***\n#> as.factor(hospital)17  0.368000   0.117549   3.131 0.001778 ** \n#> as.factor(hospital)18  0.222772   0.136932   1.627 0.103972    \n#> as.factor(month)2     -0.013209   0.046752  -0.283 0.777577    \n#> as.factor(month)3      0.005673   0.046752   0.121 0.903443    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 0.7471 on 1512 degrees of freedom\n#> Multiple R-squared:  0.4626,\tAdjusted R-squared:  0.4558 \n#> F-statistic: 68.49 on 19 and 1512 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n2. Linear regression on treated hospitals after introduction\n\n\n::: {.cell hash='08_did_cache/html/unnamed-chunk-5_70788fe7162e0472755e0aaf42f84e06'}\n\n```{.r .cell-code}\nsummary(lm(satis ~ as.factor(hospital) + as.factor(month), data = df_A2_lm))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satis ~ as.factor(hospital) + as.factor(month), \n#>     data = df_A2_lm)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -2.9249 -0.5702  0.0051  0.5312  4.3010 \n#> \n#> Coefficients:\n#>                       Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)            3.93810    0.09656  40.785  < 2e-16 ***\n#> as.factor(hospital)2   0.52824    0.12866   4.106 4.24e-05 ***\n#> as.factor(hospital)3   0.61426    0.13215   4.648 3.64e-06 ***\n#> as.factor(hospital)4   0.14369    0.12316   1.167 0.243517    \n#> as.factor(hospital)5  -0.01664    0.12316  -0.135 0.892553    \n#> as.factor(hospital)6   0.52712    0.12316   4.280 1.99e-05 ***\n#> as.factor(hospital)7   1.47379    0.11902  12.383  < 2e-16 ***\n#> as.factor(hospital)8   0.09652    0.12712   0.759 0.447804    \n#> as.factor(hospital)9  -1.48573    0.13033 -11.400  < 2e-16 ***\n#> as.factor(hospital)10  1.79278    0.12866  13.935  < 2e-16 ***\n#> as.factor(hospital)11  0.27968    0.12712   2.200 0.027945 *  \n#> as.factor(hospital)12 -0.11687    0.13033  -0.897 0.369994    \n#> as.factor(hospital)13  0.52838    0.12570   4.204 2.78e-05 ***\n#> as.factor(hospital)14  0.32493    0.13215   2.459 0.014052 *  \n#> as.factor(hospital)15  0.01112    0.13215   0.084 0.932978    \n#> as.factor(hospital)16  1.45179    0.12866  11.284  < 2e-16 ***\n#> as.factor(hospital)17  0.47909    0.13414   3.571 0.000366 ***\n#> as.factor(hospital)18  0.08378    0.15626   0.536 0.591934    \n#> as.factor(month)5      0.04133    0.06161   0.671 0.502359    \n#> as.factor(month)6      0.01224    0.06161   0.199 0.842484    \n#> as.factor(month)7      0.03594    0.06161   0.583 0.559682    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 0.8525 on 1511 degrees of freedom\n#> Multiple R-squared:  0.4118,\tAdjusted R-squared:  0.404 \n#> F-statistic: 52.88 on 20 and 1511 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n3. Linear regression on control hospitals\n\n\n::: {.cell hash='08_did_cache/html/unnamed-chunk-6_45860b785b64650305725dd7391fcbea'}\n\n```{.r .cell-code}\nsummary(lm(satis ~ as.factor(hospital) + as.factor(month), data = df_B_lm))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satis ~ as.factor(hospital) + as.factor(month), \n#>     data = df_B_lm)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -2.7339 -0.4212  0.0041  0.4310  2.9810 \n#> \n#> Coefficients:\n#>                        Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)            2.422814   0.056570  42.828  < 2e-16 ***\n#> as.factor(hospital)20  0.792689   0.074240  10.677  < 2e-16 ***\n#> as.factor(hospital)21  1.939639   0.078279  24.778  < 2e-16 ***\n#> as.factor(hospital)22  1.544617   0.077123  20.028  < 2e-16 ***\n#> as.factor(hospital)23  1.447022   0.076074  19.021  < 2e-16 ***\n#> as.factor(hospital)24  0.437176   0.080987   5.398 7.10e-08 ***\n#> as.factor(hospital)25  1.391775   0.086459  16.098  < 2e-16 ***\n#> as.factor(hospital)26  0.959549   0.074240  12.925  < 2e-16 ***\n#> as.factor(hospital)27  0.346647   0.072003   4.814 1.53e-06 ***\n#> as.factor(hospital)28  1.457297   0.078279  18.617  < 2e-16 ***\n#> as.factor(hospital)29  0.993853   0.075117  13.231  < 2e-16 ***\n#> as.factor(hospital)30  0.577380   0.088835   6.499 8.99e-11 ***\n#> as.factor(hospital)31  1.257387   0.074240  16.937  < 2e-16 ***\n#> as.factor(hospital)32  0.421956   0.075117   5.617 2.06e-08 ***\n#> as.factor(hospital)33  0.291327   0.074240   3.924 8.84e-05 ***\n#> as.factor(hospital)34  0.744889   0.070213  10.609  < 2e-16 ***\n#> as.factor(hospital)35  1.099413   0.072003  15.269  < 2e-16 ***\n#> as.factor(hospital)36  2.883444   0.072691  39.667  < 2e-16 ***\n#> as.factor(hospital)37  0.885705   0.086459  10.244  < 2e-16 ***\n#> as.factor(hospital)38  0.658496   0.073435   8.967  < 2e-16 ***\n#> as.factor(hospital)39  0.721805   0.077123   9.359  < 2e-16 ***\n#> as.factor(hospital)40  1.866835   0.073435  25.422  < 2e-16 ***\n#> as.factor(hospital)41  0.595567   0.072003   8.271  < 2e-16 ***\n#> as.factor(hospital)42  1.626439   0.079560  20.443  < 2e-16 ***\n#> as.factor(hospital)43 -0.027131   0.076074  -0.357    0.721    \n#> as.factor(hospital)44  0.779714   0.084396   9.239  < 2e-16 ***\n#> as.factor(hospital)45  0.531552   0.072003   7.382 1.86e-13 ***\n#> as.factor(hospital)46  0.823793   0.077123  10.682  < 2e-16 ***\n#> as.factor(month)2     -0.007044   0.035018  -0.201    0.841    \n#> as.factor(month)3      0.033570   0.035018   0.959    0.338    \n#> as.factor(month)4      0.018785   0.035018   0.536    0.592    \n#> as.factor(month)5     -0.021115   0.035018  -0.603    0.547    \n#> as.factor(month)6      0.009121   0.035018   0.260    0.795    \n#> as.factor(month)7     -0.020344   0.035018  -0.581    0.561    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 0.6632 on 4270 degrees of freedom\n#> Multiple R-squared:  0.4899,\tAdjusted R-squared:  0.4859 \n#> F-statistic: 124.3 on 33 and 4270 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n`as.factor()` converts a vector object to a factor. We specify a regressor using `as.factor()` when the regressor is a categorical variable. We want R to treat the variable as a categorical one instead as a numeric one. In our case, the regressors \"Hospital ID\" and \"Month\" are categorical variables, thus we need to use `as.factor()`.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}