{
  "hash": "3d210efa7b9c2552064eb97b5c8d375f",
  "result": {
    "markdown": "---\ntitle: \"Instrumental Variables\"\n---\n\n\n\n\n## DAG\n\n\n::: {.cell hash='09_iv_cache/html/unnamed-chunk-2_aefb1db6f793c4d204fde3d81d3b4cb0'}\n\n```{.r .cell-code}\n# Randomized encouragement trial \nrand_enc_dag <- dagify(\n  Y ~ X,\n  Z ~ Y,\n  coords = list(x = c(X = 1, Y = 3, Z = 5),\n                y = c(X = 1, Y = 1, Z = 1)),\n  labels = list(X = \"randomly encouraged\",\n                Y = \"use feature\",\n                Z = \"time spent on app\")\n)\n\n# Plot DAG\nggdag(rand_enc_dag) +\n  theme_dag() +\n  geom_dag_point(color = \"lightblue\") +\n  geom_dag_text(color = \"black\") +\n  geom_dag_edges(edge_color = \"black\") +\n  geom_dag_label_repel(aes(label = label))\n```\n\n::: {.cell-output-display}\n![](09_iv_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n## Naive, biased estimate\n\nA naive biased estimate obtained by regressing `time_spent` on `used_ftr`.\n\n\n::: {.cell hash='09_iv_cache/html/unnamed-chunk-3_b0cbec37b9c3a1e8ea77137799b7e3bb'}\n\n```{.r .cell-code}\nmodel_naive <- lm(time_spent ~ used_ftr, data = rand_enc)\nsummary(model_naive)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = time_spent ~ used_ftr, data = rand_enc)\n#> \n#> Residuals:\n#>      Min       1Q   Median       3Q      Max \n#> -20.4950  -3.5393   0.0158   3.5961  20.5051 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept) 18.86993    0.06955   271.3   <2e-16 ***\n#> used_ftr    10.82269    0.10888    99.4   <2e-16 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 5.351 on 9998 degrees of freedom\n#> Multiple R-squared:  0.497,\tAdjusted R-squared:  0.497 \n#> F-statistic:  9881 on 1 and 9998 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n## Instrumental variable estimation\n\n\n::: {.cell hash='09_iv_cache/html/unnamed-chunk-4_56674f20c7e0b98b8675c9b06355da09'}\n\n```{.r .cell-code}\n# Compute correlations\ncor(rand_enc) %>% round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>            rand_enc used_ftr time_spent\n#> rand_enc       1.00     0.20       0.13\n#> used_ftr       0.20     1.00       0.71\n#> time_spent     0.13     0.71       1.00\n```\n:::\n\n```{.r .cell-code}\nrand_enc_filtered <- dplyr::filter(rand_enc, used_ftr==0)\ncor(rand_enc_filtered[\"rand_enc\"], rand_enc_filtered[\"time_spent\"]) %>% round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>          time_spent\n#> rand_enc      -0.02\n```\n:::\n:::\n\nFrom the correlation matrix, we can see that there is a positive correlation between `rand_enc` and `used_ftr`, which is also called first-stage and confirms the relevance of our instrument. The randomized encouragement does affect (positively) decision to test the new feature of users. This is assumption \"Instrument relevance\". However, since the association between `rand_enc` and `used_ftr` is not so strong, the instrument is not so powerful.\n\nFor the partly testable assumption \"Excludability\", the conditional correlation between `rand_enc` and `time_spent` given `used_ftr` suggests a very weak negative linear relationship between `rand_enc` and `time_spent` when `used_ftr` is held constant. The correlation coefficient is close to zero, indicating that the instrument `rand_enc` influences the outcome of `time_spent` only through the treatment variable `used_ftr`.\n\nIn conclusion, instrumental variable estimation is an adequate procedure for the given situation.\n\n## IV estimate using 2SLS\n\n\n::: {.cell hash='09_iv_cache/html/unnamed-chunk-5_575be0d8b27318cbf25c1b84f9bf8d13'}\n\n```{.r .cell-code}\n# First stage\nfirst_stage <- lm(used_ftr ~ rand_enc, data = rand_enc)\nsummary(first_stage)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = used_ftr ~ rand_enc, data = rand_enc)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -0.5071 -0.3062 -0.3062  0.4929  0.6938 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept) 0.306164   0.006851   44.69   <2e-16 ***\n#> rand_enc    0.200940   0.009624   20.88   <2e-16 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 0.4811 on 9998 degrees of freedom\n#> Multiple R-squared:  0.04178,\tAdjusted R-squared:  0.04169 \n#> F-statistic:   436 on 1 and 9998 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell hash='09_iv_cache/html/unnamed-chunk-6_2eacc3c816fd7eff5659e01efa4b9e1c'}\n\n```{.r .cell-code}\n# Predicted 'probabilities' from first stage\npred_fs <- predict(first_stage)\n\n# Create table with predictions and actual decisions\npred_vs_actl <- tibble(\n  pred = pred_fs,\n  actl = rand_enc$used_ftr\n)\n\n# Plot predictions vs original\nggplot(pred_vs_actl, aes(x = pred, y = actl, color = as.factor(actl))) +\n  geom_jitter(alpha = .5) +\n  scale_color_discrete(labels = c(\"Control Group\", \"Treatment Group\")) +\n    theme(legend.title = element_blank())\n```\n\n::: {.cell-output-display}\n![](09_iv_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='09_iv_cache/html/unnamed-chunk-7_2a72bb9a6e50bc059f59c5445c658f15'}\n\n```{.r .cell-code}\n# Second stage\nsecond_stage <- lm(rand_enc$time_spent ~ first_stage$fitted.values)\nsummary(second_stage)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = rand_enc$time_spent ~ first_stage$fitted.values)\n#> \n#> Residuals:\n#>      Min       1Q   Median       3Q      Max \n#> -25.8757  -5.4714  -0.3263   5.3807  25.6541 \n#> \n#> Coefficients:\n#>                           Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)                19.3124     0.3129   61.72   <2e-16 ***\n#> first_stage$fitted.values   9.7382     0.7447   13.08   <2e-16 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 7.482 on 9998 degrees of freedom\n#> Multiple R-squared:  0.01681,\tAdjusted R-squared:  0.01672 \n#> F-statistic:   171 on 1 and 9998 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell hash='09_iv_cache/html/unnamed-chunk-8_b198df793e7e5346f1806ba23df6dc22'}\n\n```{.r .cell-code}\n# Using our instrument (rand_enc), we try to eliminate the bias induced by the omitted variable. If all assumptions regarding the validity of our instrument are met, the resulting coefficient should be close to what we have defined above.\nmodel_iv <- iv_robust(time_spent ~ used_ftr | rand_enc, data = rand_enc)\nsummary(model_iv)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> iv_robust(formula = time_spent ~ used_ftr | rand_enc, data = rand_enc)\n#> \n#> Standard error type:  HC2 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value  Pr(>|t|) CI Lower CI Upper   DF\n#> (Intercept)   19.312     0.2248   85.89 0.000e+00   18.872    19.75 9998\n#> used_ftr       9.738     0.5353   18.19 8.716e-73    8.689    10.79 9998\n#> \n#> Multiple R-squared:  0.4921 ,\tAdjusted R-squared:  0.492 \n#> F-statistic:   331 on 1 and 9998 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThe naive estimate of `used_ftr` is $10.82269$ and the IV estimate is $9.738$. Since the naive estimate is $1.08469$ larger than the IV estimate, it is biased and it has an upward bias.\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}